name: aloha
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda
  - pyquaternion
  - pyyaml
  - rospkg
  - pexpect
  - mujoco=2.3.7
  - dm_control=1.0.14
  - matplotlib
  - einops
  - packaging
  - h5py
  - ipython
